services:
  deepseek-server:
    build: .
    container_name: deepseek_server
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=deepseek-ai/deepseek-coder-1.3b-base
      - USE_QUANTIZATION=true
      - HOST=0.0.0.0
      - PORT=8000
      - TRANSFORMERS_CACHE=/app/cache/huggingface
      - HF_HOME=/app/cache/huggingface
      - HUGGINGFACE_HUB_CACHE=/app/cache/huggingface
    volumes:
      - model_cache:/app/cache/huggingface
      - logs_data:/app/logs
    restart: unless-stopped
    x-tinkr:
      cpu: 2048 
      memory: 4096  
      network:
        public: false  
      ports:
        deepseek-api:
          port: 8000
          protocol: http
          public: true
          healthcheck:
            timeout: 30
            interval: 60
            path: /health
            retries: 5
            success_code: 200-299
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 300s  # Model loading takes time

volumes:
  model_cache:
    driver: local
  logs_data:
    driver: local