version: '3.8'

services:
  deepseek-server:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=deepseek-ai/deepseek-coder-1.3b-base
      - USE_QUANTIZATION=true
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - model_cache:/home/deepseek/.cache/huggingface
      - ./logs:/app/logs
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  model_cache:
    driver: local