version: '3.8'
services:
  deepseek-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=deepseek-ai/deepseek-coder-1.3b-base
      - USE_QUANTIZATION=true
      - TRANSFORMERS_CACHE=/app/cache/huggingface
      - HF_HOME=/app/cache/huggingface
      - HUGGINGFACE_HUB_CACHE=/app/cache/huggingface
    volumes:
      - model_cache:/app/cache/huggingface
      - ./logs:/app/logs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 600s  # 10 minutes for model download

volumes:
  model_cache:
    driver: local